#!/usr/bin/env python3
"""Build a self-contained Cloudflare Worker with all site files embedded inline."""
import base64
import json
import os
from pathlib import Path

SITE_DIR = Path("/workspace/site")
OUT_WORKER = Path("/workspace/worker_bundled.js")

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
}


def collect_files(root: Path):
    files = []
    for p in root.rglob("*"):
        if p.is_file() and not p.name.startswith("."):
            rel = "/" + str(p.relative_to(root)).replace("\\", "/")
            files.append((rel, p))
    return sorted(files)


def main():
    files = collect_files(SITE_DIR)
    entries = []
    for url_path, file_path in files:
        data = file_path.read_bytes()
        b64 = base64.b64encode(data).decode("ascii")
        ext = file_path.suffix.lower()
        ct = CONTENT_TYPES.get(ext, "application/octet-stream")
        entries.append({"path": url_path, "b64": b64, "ct": ct, "size": len(data)})
        print(f"  {url_path}  ({len(data)} bytes, {ct})")

    # Build worker script
    # Use ES module syntax with default export fetch handler
    routes_json = json.dumps(entries, ensure_ascii=False)

    worker_code = """// Self-contained Worker serving site files from inline base64 payload.
// Auto-generated by build_worker.py
const ROUTES = """ + routes_json + """;

export default {
  async fetch(request) {
    const u = new URL(request.url);
    let p = u.pathname;
    if (p === '/' || p === '') p = '/index.html';
    // try exact match first
    let entry = ROUTES.find(r => r.path === p);
    // fallback: directory index
    if (!entry && !p.endsWith('/')) {
      const idx = p + '/index.html';
      entry = ROUTES.find(r => r.path === idx);
    }
    if (!entry) {
      // try as directory with trailing slash
      const idx = p + (p.endsWith('/') ? '' : '/') + 'index.html';
      entry = ROUTES.find(r => r.path === idx);
    }
    if (!entry) {
      return new Response('Not Found: ' + p, { status: 404, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
    }
    const bytes = atob(entry.b64);
    const buf = new Uint8Array(bytes.length);
    for (let i = 0; i < bytes.length; i++) buf[i] = bytes.charCodeAt(i);
    const headers = new Headers({
      'Content-Type': entry.ct,
      'Cache-Control': 'public, max-age=3600',
      'Access-Control-Allow-Origin': '*'
    });
    return new Response(buf, { headers });
  }
};
"""

    OUT_WORKER.write_text(worker_code, encoding="utf-8")
    size = OUT_WORKER.stat().st_size
    print(f"\nWorker script written: {OUT_WORKER} ({size} bytes, {size/1024:.1f} KB)")
    print(f"Embedded {len(entries)} files")


if __name__ == "__main__":
    main()
