package com.example.oddeven;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

/**
 * @class OddEvenApplication
 * @brief 奇偶数判断软件主类
 * 
 * 这是一个功能完整的奇偶数判断软件，展示了Java语言的核心特性和语法特点。
 * 包括面向对象编程、接口与抽象类、泛型、Lambda表达式、集合框架、异常处理等。
 * 
 * @author Generated by TRAE AI Assistant
 * @date 2026-07-15
 * @version 1.0
 */
public class OddEvenApplication implements OddEvenApplication {
    
    /**
     * @brief 程序入口方法（main方法）
     * 
     * Java程序的主入口，展示基本程序结构。
     * 
     * @param args 命令行参数
     */
    public static void main(String[] args) {
        System.out.println("========== Java奇偶数判断软件 ==========");
        System.out.println("版本: 1.0");
        System.out.println("作者: TRAE AI Assistant");
        System.out.println("========================================\n");
        
        // 创建应用实例并启动
        OddEvenApplication app = new OddEvenApplication();
        app.start();
    }
    
    /**
     * @brief 启动应用程序
     * 
     * 展示Java的异常处理机制（try-catch-finally）。
     */
    @Override
    public void start() {
        BufferedReader reader = null;
        
        try {
            // 展示Java输入输出流操作
            reader = new BufferedReader(new InputStreamReader(System.in));
            
            // 运行预设测试用例
            runPresetTests();
            
            // 用户交互循环
            while (true) {
                System.out.println("\n请选择操作：");
                System.out.println("1. 输入数字进行判断");
                System.out.println("2. 运行预设测试用例");
                System.out.println("3. 批量判断");
                System.out.println("4. 退出程序");
                System.out.print("请输入选项(1-4): ");
                
                String choice = reader.readLine();
                
                // 验证空输入
                if (choice.trim().isEmpty()) {
                    System.out.println("输入不能为空，请重新输入");
                    continue;
                }
                
                // 处理空输入或EOF情况
                if (choice == null) {
                    System.out.println("\n程序即将退出，感谢使用！");
                    return;
                }
                
                // 展示Java控制流语句（switch-case）
                switch (choice.trim()) {
                    case "1":
                        handleSingleInput(reader);
                        break;
                    case "2":
                        runPresetTests();
                        break;
                    case "3":
                        handleBatchInput(reader);
                        break;
                    case "4":
                        System.out.println("程序即将退出，感谢使用！");
                        return;
                    default:
                        System.out.println("无效选项，请输入1-4之间的数字");
                }
            }
            
        } catch (IOException e) {
            // 展示Java异常处理机制
            System.err.println("输入输出错误: " + e.getMessage());
        } finally {
            // 展示Java finally语句的使用
            try {
                if (reader != null) {
                    reader.close();
                    System.out.println("资源已释放");
                }
            } catch (IOException e) {
                System.err.println("关闭资源时发生错误: " + e.getMessage());
            }
        }
    }
    
    /**
     * @brief 处理单个数字输入
     * 
     * 展示Java异常处理机制（NumberFormatException）。
     * 
     * @param reader BufferedReader对象
     * @throws IOException IO异常
     */
    private void handleSingleInput(BufferedReader reader) throws IOException {
        System.out.print("\n请输入一个整数: ");
        String input = reader.readLine();
        
        try {
            // 展示Java基本数据类型与包装类的使用
            int number = Integer.parseInt(input);
            
            // 展示Java多态特性：使用接口引用指向不同实现
            EvenOddChecker[] checkers = {
                new ModuloChecker(),
                new BitwiseChecker()
            };
            
            for (EvenOddChecker checker : checkers) {
                System.out.println("\n--- 使用 " + checker.getAlgorithmName() + " ---");
                System.out.println(checker.getResultDescription(number));
                
                // 展示Java控制流语句（if-else）
                if (checker.isEven(number)) {
                    System.out.println("isEven(" + number + ") = true");
                } else {
                    System.out.println("isEven(" + number + ") = false");
                }
                
                if (checker.isOdd(number)) {
                    System.out.println("isOdd(" + number + ") = true");
                } else {
                    System.out.println("isOdd(" + number + ") = false");
                }
            }
            
            // 使用扩展判断器
            ExtendedChecker extendedChecker = new ExtendedChecker();
            System.out.println("\n--- 使用扩展判断器 ---");
            System.out.println(extendedChecker.checkAndReport(number));
            
        } catch (NumberFormatException e) {
            // 展示Java异常处理机制
            System.err.println("错误：输入不是有效的整数，请重新输入");
            System.err.println("异常信息: " + e.getMessage());
        }
    }
    
    /**
     * @brief 处理批量输入
     * 
     * 展示Java循环结构（for循环）和集合框架的应用。
     * 
     * @param reader BufferedReader对象
     * @throws IOException IO异常
     */
    private void handleBatchInput(BufferedReader reader) throws IOException {
        System.out.print("\n请输入多个整数，用空格分隔: ");
        String input = reader.readLine();
        
        // 展示Java字符串操作和循环结构
        String[] parts = input.split("\\s+");
        List<Integer> numbers = new ArrayList<>();
        
        for (String part : parts) {
            try {
                numbers.add(Integer.parseInt(part));
            } catch (NumberFormatException e) {
                System.out.println("警告: '" + part + "' 不是有效的整数，已忽略");
            }
        }
        
        if (numbers.isEmpty()) {
            System.out.println("没有有效的输入数据");
            return;
        }
        
        // 使用工具类的批量判断方法
        System.out.println("\n--- 批量判断结果 ---");
        List<String> results = CheckerUtils.batchCheck(numbers);
        
        for (String result : results) {
            System.out.println(result);
        }
        
        // 统计结果
        int[] counts = CheckerUtils.countEvensAndOdds(numbers);
        System.out.println("\n统计结果:");
        System.out.println("偶数数量: " + counts[0]);
        System.out.println("奇数数量: " + counts[1]);
        
        // 展示泛型和Lambda表达式的使用
        List<Integer> evens = CheckerUtils.filterEvens(numbers);
        List<Integer> odds = CheckerUtils.filterOdds(numbers);
        
        System.out.println("\n偶数列表: " + evens);
        System.out.println("奇数列表: " + odds);
    }
    
    /**
     * @brief 运行预设测试用例
     * 
     * 展示Java的测试用例设计，覆盖正数、负数和零的情况。
     */
    private void runPresetTests() {
        System.out.println("\n========== 运行预设测试用例 ==========");
        
        // 测试用例1：正数测试
        System.out.println("\n测试用例1: 正数测试");
        testNumber(100);
        testNumber(123);
        
        // 测试用例2：负数测试
        System.out.println("\n测试用例2: 负数测试");
        testNumber(-50);
        testNumber(-7);
        
        // 测试用例3：零值测试
        System.out.println("\n测试用例3: 零值测试");
        testNumber(0);
        
        // 测试用例4：边界值测试（Integer.MAX_VALUE和Integer.MIN_VALUE）
        System.out.println("\n测试用例4: 边界值测试");
        testNumber(Integer.MAX_VALUE);
        testNumber(Integer.MIN_VALUE);
        
        // 测试用例5：连续数字测试（展示循环结构）
        System.out.println("\n测试用例5: 连续数字测试 (-5 到 5)");
        for (int i = -5; i <= 5; i++) {
            testNumber(i);
        }
        
        System.out.println("\n========== 测试用例执行完毕 ==========");
    }
    
    /**
     * @brief 测试单个数字
     * 
     * 使用两种算法进行判断，并验证结果一致性。
     * 
     * @param number 待测试的整数
     */
    private void testNumber(int number) {
        // 创建两种不同的判断器（展示多态性）
        EvenOddChecker moduloChecker = new ModuloChecker();
        EvenOddChecker bitwiseChecker = new BitwiseChecker();
        
        boolean moduloResult = moduloChecker.isEven(number);
        boolean bitwiseResult = bitwiseChecker.isEven(number);
        
        // 验证两种算法结果一致
        if (moduloResult == bitwiseResult) {
            String result = moduloResult ? "偶数" : "奇数";
            System.out.println(String.format("  ✓ %d -> %s（两种算法结果一致）", number, result));
        } else {
            System.out.println(String.format("  ✗ %d -> 算法结果不一致！", number));
            System.out.println(String.format("    模运算: %s, 位运算: %s", 
                moduloResult ? "偶数" : "奇数", 
                bitwiseResult ? "偶数" : "奇数"));
        }
    }
    
    /**
     * @brief 展示Java特性摘要
     * 
     * 总结本程序使用的Java核心特性。
     */
    private void showJavaFeatures() {
        System.out.println("\n========== Java核心特性展示 ==========");
        System.out.println("1. 面向对象编程: 封装、继承、多态");
        System.out.println("2. 接口: EvenOddChecker接口定义规范");
        System.out.println("3. 抽象类: AbstractChecker提供模板方法");
        System.out.println("4. 泛型: CheckerUtils.filterEvens/filterOdds");
        System.out.println("5. Lambda表达式: Stream API中的map/filter");
        System.out.println("6. 集合框架: ArrayList, List");
        System.out.println("7. 异常处理: try-catch-finally");
        System.out.println("8. 方法重载: isEven(int)/isEven(Integer)");
        System.out.println("9. 方法重写: 子类实现接口方法");
        System.out.println("10. 输入输出流: BufferedReader, InputStreamReader");
        System.out.println("11. 控制流: if-else, switch-case, for, while");
        System.out.println("12. 枚举: CheckerUtils.EvenOddResult");
        System.out.println("======================================");
    }
}